"""
Xoe-NovAi Foundation Stack Core Module
Provides integrated circuit breakers, health monitoring, and graceful degradation.
"""

from .circuit_breakers import (
    CircuitBreaker,
    CircuitBreakerError,
    CircuitBreakerConfig,
    CircuitState,
    CircuitStateData,
    CircuitStateStore,
    RedisCircuitStateStore,
    InMemoryCircuitStateStore,
    GracefulDegradationManager,
    create_redis_circuit_breaker,
    create_inmemory_circuit_breaker,
    fallback_return_none,
    fallback_return_empty_dict,
    fallback_return_empty_list,
    fallback_raise_service_unavailable,
    RedisConnectionManager,
    CircuitBreakerStateManager,
    CircuitBreakerRegistry,
    create_circuit_breaker_registry,
    DegradationStrategy,
    FallbackStrategy,
    CacheFirstStrategy,
    DegradedModeStrategy,
    CircuitBreakerStrategy,
    DegradationManager,
    ServiceDegradationManager,
    IntegratedDegradationManager,
    create_llm_degradation_manager,
    create_redis_degradation_manager,
    create_vector_search_degradation_manager
)

from .health import (
    HealthChecker,
    HealthStatus,
    HealthCheckResult,
    ServiceHealth,
    HTTPHealthChecker,
    RedisHealthChecker,
    DatabaseHealthChecker,
    CustomHealthChecker,
    HealthMonitor,
    create_rag_api_health_checker,
    create_chainlit_ui_health_checker,
    create_redis_health_checker,
    create_vikunja_health_checker,
    create_caddy_health_checker,
    RecoveryManager,
    RecoveryAction,
    RecoveryRule,
    RecoveryAttempt,
    IntegratedRecoveryManager,
    create_redis_recovery_rules,
    create_rag_api_recovery_rules,
    create_chainlit_ui_recovery_rules,
    create_vikunja_recovery_rules
)

__all__ = [
    # Circuit Breakers
    'CircuitBreaker',
    'CircuitBreakerError',
    'CircuitBreakerConfig',
    'CircuitState',
    'CircuitStateData',
    'CircuitStateStore',
    'RedisCircuitStateStore',
    'InMemoryCircuitStateStore',
    'GracefulDegradationManager',
    'create_redis_circuit_breaker',
    'create_inmemory_circuit_breaker',
    'fallback_return_none',
    'fallback_return_empty_dict',
    'fallback_return_empty_list',
    'fallback_raise_service_unavailable',
    'RedisConnectionManager',
    'CircuitBreakerStateManager',
    'CircuitBreakerRegistry',
    'create_circuit_breaker_registry',
    'DegradationStrategy',
    'FallbackStrategy',
    'CacheFirstStrategy',
    'DegradedModeStrategy',
    'CircuitBreakerStrategy',
    'DegradationManager',
    'ServiceDegradationManager',
    'IntegratedDegradationManager',
    'create_llm_degradation_manager',
    'create_redis_degradation_manager',
    'create_vector_search_degradation_manager',
    
    # Health Monitoring
    'HealthChecker',
    'HealthStatus',
    'HealthCheckResult',
    'ServiceHealth',
    'HTTPHealthChecker',
    'RedisHealthChecker',
    'DatabaseHealthChecker',
    'CustomHealthChecker',
    'HealthMonitor',
    'create_rag_api_health_checker',
    'create_chainlit_ui_health_checker',
    'create_redis_health_checker',
    'create_vikunja_health_checker',
    'create_caddy_health_checker',
    'RecoveryManager',
    'RecoveryAction',
    'RecoveryRule',
    'RecoveryAttempt',
    'IntegratedRecoveryManager',
    'create_redis_recovery_rules',
    'create_rag_api_recovery_rules',
    'create_chainlit_ui_recovery_rules',
    'create_vikunja_recovery_rules'
]

# Version information
__version__ = "1.0.0"
__author__ = "Xoe-NovAi Foundation Stack"
__description__ = "Integrated circuit breakers, health monitoring, and graceful degradation"