#!/usr/bin/env bash
# xnai: zRAM Health Check → Prometheus textfile collector
# Writes metrics to /var/lib/node_exporter/textfile_collector/xnai_zram.prom (Prometheus textfile format)

set -euo pipefail
OUTPUT_DIR="/var/lib/node_exporter/textfile_collector"
TMPFILE="/tmp/xnai_zram.prom.$$"
FINAL="$OUTPUT_DIR/xnai_zram.prom"

# Helper: human-readable size to bytes
hr2bytes() {
  v="$1"
  # strip commas
  v="${v//,/}"
  case "${v: -1}" in
    K|k) echo $(( ${v%?} * 1024 )) ;;
    M|m) echo $(( ${v%?} * 1024 * 1024 )) ;;
    G|g) echo $(( ${v%?} * 1024 * 1024 * 1024 )) ;;
    T|t) echo $(( ${v%?} * 1024 * 1024 * 1024 * 1024 )) ;;
    *) echo "$v" ;;
  esac
}

# Default metric values
compression_ratio=0
used_bytes=0
uncompressed_bytes=0
total_bytes=0
streams=0
algorithm="unknown"

# Parse zramctl output robustly using header mapping
if zramctl_out=$(zramctl 2>/dev/null) && echo "$zramctl_out" | grep -q zram0; then
  # header -> find column indices
  header=$(echo "$zramctl_out" | head -n1)
  # build awk that extracts by header name
  read -r data compr total alg streams <<< $(echo "$zramctl_out" | awk 'NR==1{for(i=1;i<=NF;i++){h[$i]=i}} NR>1{print $(h["DATA"]), $(h["COMPR"]), $(h["TOTAL"]), $(h["ALGORITHM"]), $(h["STREAMS"]); exit}') || true

  # convert to bytes
  uncompressed_bytes=$(hr2bytes "$data" 2>/dev/null || echo 0)
  compressed_bytes=$(hr2bytes "$compr" 2>/dev/null || echo 0)
  total_bytes=$(hr2bytes "$total" 2>/dev/null || echo 0)
  streams=$(echo "$streams" | tr -dc '0-9' || echo 0)
  algorithm=$(echo "$alg" | tr -d '[:space:]' || echo unknown)

  # calculate ratio
  if [ -n "$compressed_bytes" ] && [ "$compressed_bytes" -gt 0 ]; then
    # use awk for floating point
    compression_ratio=$(awk "BEGIN{printf \"%.2f\", ($uncompressed_bytes == 0 ? 0 : $uncompressed_bytes / $compressed_bytes)}")
  else
    compression_ratio=0
  fi
  used_bytes=$total_bytes
fi

# Emit Prometheus textfile
cat > "$TMPFILE" <<EOF
# xnai zRAM metrics (generated by scripts/zram-health-check.sh)
xnai_zram_compression_ratio ${compression_ratio}
xnai_zram_used_bytes ${used_bytes}
xnai_zram_uncompressed_bytes_total ${uncompressed_bytes}
xnai_zram_streams ${streams}
xnai_zram_algorithm{alg="${algorithm}"} 1
# unix timestamp
xnai_zram_collected_ts $(date +%s)
EOF

# Atomically move into place if writable, else print to stdout
if [ -d "$OUTPUT_DIR" ] && [ -w "$OUTPUT_DIR" ]; then
  mkdir -p "$OUTPUT_DIR" 2>/dev/null || true
  mv "$TMPFILE" "$FINAL"
  chmod 644 "$FINAL" 2>/dev/null || true
  echo "Wrote Prometheus metrics to $FINAL"
else
  echo "node_exporter textfile collector not writable; outputting metrics to stdout:" >&2
  cat "$TMPFILE"
  rm -f "$TMPFILE" || true
fi

# Optional: show container memory usage if runtime available
if command -v podman &>/dev/null; then
  podman stats --no-stream --format "table {{.Name}}\t{{.MemUsage}}\t{{.MemPerc}}" || true
elif command -v docker &>/dev/null; then
  docker stats --no-stream --format "table {{.Name}}\t{{.MemUsage}}\t{{.MemPerc}}" || true
fi

# Basic system status (helpful for quick debugging)
free -h || true
zramctl || true

exit 0
