#!/usr/bin/env bash
# xnai: zRAM Health Check → Prometheus textfile collector
# Purpose: Aggregates metrics from all zRAM devices (zram0, zram1, etc.)
# Writes metrics to /var/lib/node_exporter/textfile_collector/xnai_zram.prom

set -euo pipefail
OUTPUT_DIR="${XNAI_ZRAM_OUTPUT_DIR:-/var/lib/node_exporter/textfile_collector}"
TMPFILE="/tmp/xnai_zram.prom.$$"
FINAL="$OUTPUT_DIR/xnai_zram.prom"

# Helper: human-readable size to bytes
hr2bytes() {
  v="$1"
  v="${v//,/}"
  case "${v: -1}" in
    K|k) echo $(( ${v%?} * 1024 )) ;;
    M|m) echo $(( ${v%?} * 1024 * 1024 )) ;;
    G|g) echo $(( ${v%?} * 1024 * 1024 * 1024 )) ;;
    T|t) echo $(( ${v%?} * 1024 * 1024 * 1024 * 1024 )) ;;
    *) echo "$v" ;;
  esac
}

# Cumulative totals
total_uncompressed_bytes=0
total_compressed_bytes=0
total_used_bytes=0
device_count=0

# Start Prometheus output
{
  echo "# xnai zRAM metrics (generated by scripts/zram-health-check.sh)"
  
  if zramctl_out=$(zramctl 2>/dev/null); then
    # Get header line to find column indices
    header=$(echo "$zramctl_out" | head -n1)
    
    # Process each device line
    while read -r line; do
      if echo "$line" | grep -q "^/dev/zram"; then
        device_name=$(echo "$line" | awk '{print $1}')
        
        # Extract columns using awk by header name
        data=$(echo "$zramctl_out" | awk -v d="$device_name" 'NR==1{for(i=1;i<=NF;i++){h[$i]=i}} $1==d{print $(h["DATA"])}')
        compr=$(echo "$zramctl_out" | awk -v d="$device_name" 'NR==1{for(i=1;i<=NF;i++){h[$i]=i}} $1==d{print $(h["COMPR"])}')
        total=$(echo "$zramctl_out" | awk -v d="$device_name" 'NR==1{for(i=1;i<=NF;i++){h[$i]=i}} $1==d{print $(h["TOTAL"])}')
        alg=$(echo "$zramctl_out" | awk -v d="$device_name" 'NR==1{for(i=1;i<=NF;i++){h[$i]=i}} $1==d{print $(h["ALGORITHM"])}')
        streams=$(echo "$zramctl_out" | awk -v d="$device_name" 'NR==1{for(i=1;i<=NF;i++){h[$i]=i}} $1==d{print $(h["STREAMS"])}')

        # Convert to bytes
        u_bytes=$(hr2bytes "$data" 2>/dev/null || echo 0)
        c_bytes=$(hr2bytes "$compr" 2>/dev/null || echo 0)
        t_bytes=$(hr2bytes "$total" 2>/dev/null || echo 0)
        
        # Add to totals
        total_uncompressed_bytes=$((total_uncompressed_bytes + u_bytes))
        total_compressed_bytes=$((total_compressed_bytes + c_bytes))
        total_used_bytes=$((total_used_bytes + t_bytes))
        device_count=$((device_count + 1))

        # Per-device metrics
        short_name=$(basename "$device_name")
        echo "xnai_zram_device_used_bytes{device=\"$short_name\", alg=\"$alg\"} $t_bytes"
        echo "xnai_zram_device_uncompressed_bytes{device=\"$short_name\"} $u_bytes"
        echo "xnai_zram_device_streams{device=\"$short_name\"} $streams"
      fi
    done <<< "$zramctl_out"
  fi

  # Aggregated metrics
  if [ "$total_compressed_bytes" -gt 0 ]; then
    compression_ratio=$(awk "BEGIN{printf \"%.2f\", $total_uncompressed_bytes / $total_compressed_bytes}")
  else
    compression_ratio=0
  fi

  echo "xnai_zram_compression_ratio ${compression_ratio}"
  echo "xnai_zram_used_bytes_total ${total_used_bytes}"
  echo "xnai_zram_uncompressed_bytes_total ${total_uncompressed_bytes}"
  echo "xnai_zram_device_count ${device_count}"
  echo "xnai_zram_collected_ts $(date +%s)"
} > "$TMPFILE"

# Atomically move into place
if [ -d "$OUTPUT_DIR" ] && [ -w "$OUTPUT_DIR" ]; then
  mv "$TMPFILE" "$FINAL"
  chmod 644 "$FINAL" 2>/dev/null || true
  echo "Wrote Prometheus metrics to $FINAL"
else
  cat "$TMPFILE"
  rm -f "$TMPFILE" || true
fi

exit 0
