"""
app/core/gmc_normalizer.py
-------------------------------------------------------------------
Gnostic Markov Chain (GMC) Normalizer
Core utility for enforcing markdown structural integrity and schema.
SESS-27.7 - Sovereign Stack
-------------------------------------------------------------------
"""

import re
import hashlib
from datetime import datetime
from typing import Dict, Optional, List

class GMCNormalizer:
    """
    Enforces strict structural and content normalization for Markdown files within the Gnostic Vault.
    Implements the 'Backslash Stripper' and 'Frontmatter Enforcer'.
    """

    FRONTMATTER_PATTERN = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
    BACKSLASH_PATTERN = re.compile(r"\\([^\\])") # Matches single backslash followed by non-backslash

    REQUIRED_FIELDS = ["type", "tags", "status", "created_date"]

    @staticmethod
    def strip_backslashes(content: str) -> str:
        """Removes single backslashes used for escaping (often hallucinatory artifacts)."""
        # Replace '\X' with 'X' where X is not a backslash
        # This is a simplification; a robust regex is needed to avoid stripping legitimate escapes
        # Ideally, we only strip backslashes before spaces or standard punctuation if that's the issue.
        # For now, let's target the known "hallucination pattern": `text \ text` or `\[link\]`
        # Safer: only strip backslash if followed by a space or punctuation
        return content.replace("\\ ", " ").replace("\\[", "[").replace("\\]", "]").replace("\\_", "_")

    @staticmethod
    def enforce_frontmatter(content: str, type_tag: str = "entity") -> str:
        """Ensures the file has a valid YAML frontmatter block."""
        match = GMCNormalizer.FRONTMATTER_PATTERN.match(content)
        
        if match:
            # Frontmatter exists, parse and validate (placeholder for full YAML parsing)
            # For now, just return as is or do minimal cleanup
            return content
        else:
            # No frontmatter, prepend a default block
            timestamp = datetime.utcnow().strftime("%Y-%m-%d")
            header = (
                "---\n"
                f"type: {type_tag}\n"
                f"tags: [autogenerated, migration]\n"
                f"status: draft\n"
                f"created_date: {timestamp}\n"
                "---\n\n"
            )
            return header + content

    @staticmethod
    def compute_rigidity_hash(content: str) -> str:
        """Computes the SHA-256 hash of the content for integrity verification."""
        return hashlib.sha256(content.encode("utf-8")).hexdigest()

    @classmethod
    def normalize(cls, content: str, type_tag: str = "entity") -> str:
        """Full normalization pipeline."""
        content = cls.strip_backslashes(content)
        content = cls.enforce_frontmatter(content, type_tag)
        return content
